version: '3.1'

services:

  wordpress:
    image: wordpress:5.2.2
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./web/docroot:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - vl_db_data:/var/lib/mysql
volumes:
  vl_db_data: